"""empty message

Revision ID: 1334c4176c3c
Revises: 6eef1b94a175
Create Date: 2019-05-29 16:32:48.357568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1334c4176c3c'
down_revision = '6eef1b94a175'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airplane',
                    sa.Column(
                        'id', sa.String(length=36), nullable=False),
                    sa.Column(
                        'created_at', sa.DateTime(), nullable=True),
                    sa.Column(
                        'updated_at', sa.DateTime(), nullable=True),
                    sa.Column(
                        'brand', sa.String(length=60), nullable=False),
                    sa.Column(
                        'model', sa.String(length=60), nullable=False),
                    sa.Column(
                        'capacity', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pk_airplane')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('airplane')
    # ### end Alembic commands ###
