"""empty message

Revision ID: 66034f09f704
Revises: 1334c4176c3c
Create Date: 2019-05-30 09:34:38.095913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66034f09f704'
down_revision = '1334c4176c3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight',
                    sa.Column(
                        'id', sa.String(length=36), nullable=False),
                    sa.Column(
                        'created_at', sa.DateTime(), nullable=True),
                    sa.Column(
                        'updated_at', sa.DateTime(), nullable=True),
                    sa.Column(
                        'airplane_id', sa.String(), nullable=False),
                    sa.Column(
                        'flying_from', sa.String(length=400), nullable=False),
                    sa.Column(
                        'flying_to', sa.String(length=400), nullable=False),
                    sa.Column(
                        'departure', sa.DateTime(), nullable=False),
                    sa.Column(
                        'arrival', sa.DateTime(), nullable=False),
                    sa.Column(
                        'date', sa.Date(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['airplane_id'], ['airplane.id'], name=op.f(
                            'flight_airplane_id_fkey')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_flight')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flight')
    # ### end Alembic commands ###
