"""empty message

Revision ID: 6eef1b94a175
Revises:
Create Date: 2019-05-28 12:44:33.541522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eef1b94a175'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.String(length=36), nullable=False),
                    sa.Column(
                        'created_at', sa.DateTime(), nullable=True),
                    sa.Column(
                        'updated_at', sa.DateTime(), nullable=True),
                    sa.Column(
                        'first_name', sa.String(length=60), nullable=False),
                    sa.Column(
                        'last_name', sa.String(length=60), nullable=False),
                    sa.Column('email', sa.String(length=250), nullable=False),
                    sa.Column(
                        'password', sa.String(length=250), nullable=False),
                    sa.Column('role', sa.Enum(
                        'user', 'admin', name='userroleenum'), nullable=False),
                    sa.Column(
                        'passport_photograph', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
                    sa.UniqueConstraint('email', name=op.f('uq_users_email')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("drop type userroleenum CASCADE")
    op.drop_table('users')
    # ### end Alembic commands ###
