"""empty message

Revision ID: 762353630b5a
Revises: e493a67d18e8
Create Date: 2019-06-21 12:16:32.344650

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '762353630b5a'
down_revision = 'e493a67d18e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        ALTER TABLE users
        ALTER COLUMN passport_photograph
        TYPE JSON
        USING passport_photograph::json''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        ALTER TABLE users
        ALTER COLUMN passport_photograph
        TYPE varchar''')
    # ### end Alembic commands ###
