"""empty message

Revision ID: e493a67d18e8
Revises: 09cb109bfdf2
Create Date: 2019-06-12 02:41:17.767075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e493a67d18e8'
down_revision = '09cb109bfdf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flights', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'flights',
        sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
